### PR TITLE
Fix Credits Transition

### LINKED ISSUE #380: Last Level to Credits Transition Broken

### PR DESCRIPTION
**Pull request by mt-xing**
### Summary 

Fixed the transition to the credits after beating the last level.
Close #380

### Testing 

Ran on Windows and it worked

### Review Focus 

Mainly main menu stuff

### CODE REVIEW

File: source/GameGraphRoot.cpp [hunk 1]
```diff
@@ -747,9 +747,9 @@ void GameGraphRoot::update(float timestep) {
 	// Rotate nearSpace about center.
 	float newPlayerAngle = ship->getDonuts().at(playerID)->getAngle();
 	float delta = (prevPlayerAngle - newPlayerAngle) * globals::PI_180;
-	delta = delta < -globals::PI
-				? delta + ship->getSize() * globals::PI_180
-				: delta > globals::PI ? delta - ship->getSize() * globals::PI_180 : delta;
+	delta = (delta < -globals::PI)
+				? (delta + ship->getSize() * globals::PI_180)
+				: (delta > globals::PI ? delta - ship->getSize() * globals::PI_180 : delta);
```
Comment (mt-xing) [inline source/GameGraphRoot.cpp:752]: This was just to make `clang-format` happy; I suspect that our CI pipeline is running a newer version of `clang-format` than Visual Studio is, because it didn't show up as a problem in VS. Nonetheless, adding this fixed it.

Comment (mt-xing) [reply source/GameGraphRoot.cpp:752]: Yep; the CI is using `llvm 11` while VS is on `llvm 10`. I'll see if there's anything I can do about that.

**Review by ssorenson130 — APPROVED** [review]
looks simple enough not to break anything
