### PR TITLE
Health fix

### LINKED ISSUE #381: Weird Health Schnanigans
Not moving when a level starts seems to keep the health from going down

### PR DESCRIPTION
**Pull request by ssorenson130**
### Summary 

Fixed the one line using the wrong timer to calculate health. 
Close #381 

### Testing 

Tested with two windows clients

### CODE REVIEW

File: source/GameMode.cpp [hunk 1]
```diff
@@ -382,11 +382,10 @@ void GameMode::updateHealth() {
 	auto& breaches = ship->getBreaches();
 
 	// Breach health drain
-	for (auto& breache : breaches) {
+	for (auto& breach : breaches) {
```
Comment (mt-xing) [inline source/GameMode.cpp:385]: nit: can we make this a `const auto&`? Since it's a smart pointer, it's good form to get the pointer itself as a `const` reference since we don't plan on reassigning the pointer.

Comment (ssorenson130) [reply source/GameMode.cpp]: sure
