### PR TITLE
Breach fix animation

### LINKED ISSUE #280: Particles on Breach Resolution

### PR DESCRIPTION
**Pull request by wenjiazhang**
### Summary 

- Added sparkle effect whenever a breach has been rolled over by matching donut
- Added `SparkleNode` which is responsible for appearing over a breach when called, playing the filmstrip, and disappearing once animation ends.
Close #280 

### Testing 
Tested on Mac and iOS.
image

### CODE REVIEW

File: source/BreachNode.cpp [hunk 1]
```diff
@@ -54,7 +62,9 @@ bool BreachNode::init(std::shared_ptr<BreachModel> breach, std::shared_ptr<Donut
 	return true;
 }
 
-bool BreachNode::isActive() { return breachModel->getHealth() > 0 || isAnimatingShrink; }
+bool BreachNode::isActive() {
+	return breachModel->getHealth() > 0 || (prevHealth == 1 && breachModel->getHealth() == 0);
```
Comment (mt-xing) [inline source/BreachNode.cpp:66]: This line should really just return `breachModel->getIsActive()`. If `isActive` becomes false before you want to scene graph node to despawn, then you should edit the game logic so that `isActive` stays true until the scene graph node can be safely despawned. It's not safe to leave scene graph nodes hanging around on screen after the model becomes inactive, because then the linked model becomes eligible to be recycled. This is how we get bugs like the -1 on the buttons.

File: source/CustomNode.h [hunk 2]
```diff
@@ -75,6 +75,7 @@ class CustomNode : public cugl::Node {
 						   onScreenAngle <= -globals::SEG_CUTOFF_ANGLE);
 	}
 
+   protected:
```
Comment (mt-xing) [inline source/CustomNode.h:78]: Why are you making these private methods protected? The child classes really aren't supposed to have to handle any of this spawn positioning code at all.

Comment (wenjiazhang) [reply source/CustomNode.h:78]: I needed to expose this to be able to let `breachNode` move its `sparkleNode` around. I found a workaround tho so I guess I can undo this.

File: source/BreachNode.cpp (hunk 1 above)
Comment (wenjiazhang) [reply source/BreachNode.cpp:66]: I did not like messing with the `isActive` method, but you have to know that the architecture is INCREDIBLY unaccommodating for animations because the nodes are written to be strictly responsive to models, which leaves very little opportunity for animation checks to run. For many of the in-game animations I've coded, I've almost always had to wrestle with the architecture because models get recycled, so it's basically impossible to implement trailing animations like the breach disappearing from health 1 into nothing. 

Here I need a one-frame window after the breach is resolved to activate the sparkle animation. However once the breach is resolved, the model and the node become inactive and `postPosition()` is no longer called. I could put some of the logic in `draw()`, but that would mean duplicate if statements and code, which kinda defeats the purpose of the `CustomNode` pipeline. Here I'm letting `isActive` be true for one extra frame after breach resolve to let `postPosition()` be executed. 

When we were discussing the `CustomNode` refactor, I said I was concerned about future code flexibilty for new features and this is the exact problem.

Comment (mt-xing) [reply source/BreachNode.cpp:66]: Doors also have to stay on screen after being resolved, and exhibits the way this architecture was designed to work with this issue. If the information is needed after the resolution of the object, the model should not report `isActive` false. As soon as it does, then the model might be reused for another spawned object, which would break the scene nodes. If you need the model to stick around for the duration of the animation (which is probably a good idea here), that logic should probably go inside the model object itself.

**Comment by wenjiazhang** [comment]
> Do we want the sparkle every single time the player rolls over a breach? I was under the impression that they weren't getting enough feedback as to when they were done patching a breach, which would imply that we only want it to spawn upon resolution.

I actually enjoy the animation whenever a breach is being fixed. It makes the controls feel more responsive because something is actually happening when you roll over your own breach. In our previous version the shrinking is quite subtle and the breach is obscured by your donut when it starts shrinking. It also makes sense to match the sound effect to the visuals. Whenever you roll over your own donut the same SFX is played so the same visual should be shown. We could have a separate animation for breach resolve. @mt-xing

**Comment by mt-xing** [comment]
> We could have a separate animation for breach resolve.

That sounds good, as long as its not too much work for you designers. It's just that the feedback from golden master was pretty explicit that we need to be much more clear about when a breach is actually resolved versus still hanging around with 1 health.

File: source/BreachNode.cpp (hunk 1 above)
Comment (wenjiazhang) [reply source/BreachNode.cpp:66]: In the case of the door I agree that it's justified to have the door height be information that is a part of the model because it affects collision, so the model can set its `isActive` field in consideration of the height. 

However, with breaches, the trailing animation has no significance to the model itself.  Once the breach's health hits zero, it no longer impacts any other models and should be for all purposes considered inactive. However, on the display side, we want a trailing animation that is purely visual effects and does not reflect the current model state. The architecture simply does not accommodate trailing animations.

Comment (mt-xing) [reply source/BreachNode.cpp:66]: Would you prefer if `CustomNode` exposed an additional lifecycle method that is called once upon a state change from active to not active? Would that make life easier?

Comment (wenjiazhang) [reply source/BreachNode.cpp:66]: Yes that would resolve the issue of the `isActive()` changes. However it would also mean duplicate code for intiating the sparkle animation.

Comment (mt-xing) [reply source/BreachNode.cpp:66]: The code to initiate the animation could always be factored into a different method inside `BreachNode`, which is then called in two places. I'll branch off this branch and work on adding that extra method. I'll ping you on Slack when I'm done.

**Comment by wenjiazhang** [comment]
> Yeah, based on golden master feedback, we definitely only want the animation upon completely fixing a breach.

It done! @mt-xing
