### PR TITLE
Fix Buttons

### LINKED ISSUE #287: Redo Button Model
With actual real height detection and such.

### PR DESCRIPTION
**Pull request by mt-xing**
# Summary 

Changed button model to compute its own height based on when jumped (passed in by `GameMode`), and edited scene graph to correctly display height.
Buttons now animate properly, trigger on land (instead of on jump), have a configurable grace period, and are no longer a massive hack.
This PR does **not** do the whole animation with buttons sinking into the ground and such on resolution, instead just making them disappear. We can do that in the future if we really want, but for now, this seems to work much better. It also hides the `-1` label that users kept seeing.
Close #287

Also cleaned up some stray unused parameters in `mib`, and reduced the frequency of network messages when buttons are on screen (it used to be that a message was broadcast by every user every frame for every active button; now messages are only broadcast on press, as intended).

# Testing 

Played on Windows; works correctly.

# Review Focus 

Changes to `ButtonModel` and `ButtonNode`, as well as `GameMode` changes concerning the buttons, are most important. A lot of other stuff is just basic cleanup.

### CODE REVIEW

File: source/ButtonModel.cpp [hunk 1]
```diff
@@ -2,6 +2,20 @@
 
 #include "Globals.h"
 
+#pragma region Animation Constants
```
Comment (wenjiazhang) [inline source/ButtonModel.cpp:5]: Can we name these with "button" in them?
